name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: arch-latest

    steps:
    - uses: actions/checkout@v4
    - name: make build
      run: make build
