name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install SDL2 dependencies
      run: |
        sudo apt-get install -y libsdl2-dev

    - uses: actions/checkout@v4
    - name: make build
      run: make build
